### ISSUE TITLE
quicklisp can't find the trivial-custom-debugger system

### ISSUE THREAD

**Issue by psilord** [phoe/trivial-custom-debugger#6]
Hello,

When writing a test system, I'll add `#:trivial-custom-debugger` to the `:depends-on` portion of the `asdf:defsystem` form, but quicklisp can't find it for some reason with an error like:

```text
12345678910111213141516171819202122debugger invoked on a ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread
#<THREAD "main thread" RUNNING {1001070113}>:
  Component #:TRIVIAL-CUSTOM-DEBUGGER not found, required by
  #<SYSTEM "colony.test">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry loading TRIVIAL-CUSTOM-DEBUGGER.
  1:                                 Retry ASDF operation.
  2: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  3:                                 Retry ASDF operation.
  4:                                 Retry ASDF operation after resetting the
                                     configuration.
  5: [ABORT                        ] Exit debugger, returning to top level.

(ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<ASDF/SYSTEM:SYSTEM "colony.test"> #:TRIVIAL-CUSTOM-DEBUGGER NIL)
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
```

If I manually type, at the repl `(ql:quickload :trivial-custom-debugger)` quicklisp till find and load the system. 

Would you happen to know why this might be and what I can do to fix it (or at least how to debug why it might be happening)?

 I'm not sure which codebase is responsible for the error: quicklisp, parachute (which uses this library and I have seen signal this error), or my own use of it.

Thank you!

**Comment by phoe** [comment]
Strange. Can you post a backtrace and/or upload your system to Quicklisp?

**Comment by psilord** [comment]
Hrm, the system is part of a much larger piece of code, here is a link to the system itself:

https://github.com/colonyengine/colony/blob/develop/colony.test.asd

which may be sufficient for you to see if I'm using something wrongly immediately.

I'll look into getting a backtrace of it. The problem only happens when trivial-custom-debugger has not already been loaded into quicklisp and I `(asdf:test-system :colony)`. This is currently happening on a friend's machine and I need to
ask him to get the backtrace. The colony.asd file is here:

https://github.com/colonyengine/colony/blob/develop/colony.asd

And you'll see the `:perform-op` on line 39.

It could just be that I've asked ASDF itself, as opposed to quicklisp, to run the test system, and in that case of course ASDF doesn't find the system because it isn't available. But it seems quicklisp somehow is still involved. I never have looked too deeply to see if the interaction between asdf and quicklisp is bidirectional or not.

Thank you!

**Comment by phoe** [comment]
> I never have looked too deeply to see if the interaction between asdf and quicklisp is bidirectional or not.

Let's rule that out first. Can you `(asdf:load-system :trivial-custom-debugger)` in a fresh REPL, without using Quicklisp?

**Comment by psilord** [comment]
Alrighty, after inspection given the inferred direction from you, it looks like the answer is simply that when I run `(asdf:test-system :colony)` and trivial-custom-debugger is not already installed into quicklisp, no quicklisp gets called and the system is not found. So, the fix is to manually install trivial-custom-debugger and anything else the testing system might need via ql:quickload. 

Thank you!
